apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: idm
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: openidm
        imagePullPolicy: Always
        resources:
          limits:
            memory: 6Gi
          requests:
            cpu: 2000m
            memory: 6Gi

