# Deploys multi-cluster DS: ds-cts and ds-idrepo
# The namespace must be identical for all regions
resources:
- ../../../../base/kustomizeConfig
- ../../multi-cluster-secrets
- ../../../../base/ds/idrepo
- ../../../../base/ds/cts 
- ../../../../base/ldif-importer

patches:
- path: base.yaml
- path: ds-cts-old.yaml
- path: ds-idrepo-old.yaml
