apiVersion: apps/v1
kind: Deployment
metadata:
  name: am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: am
  template:
    metadata:
      labels:
        app: am
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      initContainers:
      # - name: fbc-init
      #   image: am
      #   volumeMounts:
      #   - mountPath: /fbc
      #     name: fbc
      #   command:
      #   - /bin/bash
      #   - -c
      #   - |
      #     cd /home/forgerock/openam
      #     cp -r .homeVersion * /fbc

      - name: config
        image: conf
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /fbc
          name: fbc
        env:
        - name: CONFIG_SERVER
          value: "config-server:50051"
        - name: "CONFIG_DIR"
          value: "/fbc"
        - name: "CONFIG_PRODUCT"
          value: "am"

      - name: truststore-init
        image: am
        imagePullPolicy: Always
        volumeMounts:
        - name: new-truststore
          mountPath: /truststore
        - name: truststore
          mountPath: /var/run/secrets/truststore
        command: ["/home/forgerock/import-pem-certs.sh"]
        env:
        - name: TRUSTSTORE_PATH
          value: /truststore/amtruststore
        - name: TRUSTSTORE_PASSWORD
          value: changeit
        - name: AM_PEM_TRUSTSTORE
          value: "/var/run/secrets/truststore/cacerts"

      containers:
      - name: openam
        image: am
        imagePullPolicy: Always
        command:
          - bash
          - /home/forgerock/docker-entrypoint.sh
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AM_STORES_SSL_ENABLED
          value: "true"
        - name: TRUSTSTORE_PATH
          value: /home/forgerock/amtruststore
        - name: TRUSTSTORE_PASSWORD
          value: changeit
        - name: AM_STORES_USER_TYPE
          value: LDAPv3ForForgeRockIAM
        - name: CATALINA_USER_OPTS
          # value: "-Dcom.forgerock.am.fileconfig.basepaths=/home/forgerock/openam/config/services,/home/forgerock/openam/fbc/config/service -Dcom.forgerock.am.fileconfig.filelocation=/home/forgerock/openam/fbc/config/service"
          # value: "-Dcom.forgerock.am.fileconfig.basepaths=/home/forgerock/openam/config/services,/home/forgerock/openam/fbc/config/service"
          # our config first, then standard docker config. Changes still go to openam/config
          # value: "-Dcom.forgerock.am.fileconfig.basepaths=/home/forgerock/openam/fbc/config/service,/home/forgerock/openam/config/services"
          # Our config first and save to our config. Results in config store not available
          # value: "-Dcom.forgerock.am.fileconfig.basepaths=/home/forgerock/openam/fbc/config/service,/home/forgerock/openam/config/services -Dcom.forgerock.am.fileconfig.filelocation=/home/forgerock/openam/fbc/config/service"
          # Suggestion from Jay
          value: "-Dcom.forgerock.am.fileconfig.basepaths=/home/forgerock/fbc/services,/home/forgerock/openam/config/services -Dcom.forgerock.am.fileconfig.filelocation=/home/forgerock/fbc/services"

        envFrom:
        - secretRef:
            name: am-env-secrets
        - configMapRef:
            name: platform-config
        - secretRef:
            name: amster-env-secrets # Needed for public amster key
        - secretRef:
            name: ds-env-secrets # passwords for cts, userstore, etc
        livenessProbe:
          httpGet:
            path: /am/json/health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /am/json/health/ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 1800Mi
            cpu: 250m
        volumeMounts:
        - name: new-truststore
          mountPath: /home/forgerock/amtruststore
          readOnly: true
          subPath: amtruststore
        - name: am-secrets
          mountPath: /var/run/secrets/am
        - name: amster-key
          mountPath: /var/run/secrets/amster
        # TODO: Check path
        - name: fbc
          mountPath: /home/forgerock/fbc
          # mountPath: /home/forgerock/openam/config
          subPath: config
      # Config saver
      - name: config-save
        image: conf
        imagePullPolicy: Always
        args: ["5"]
        env:
        - name: CONFIG_SERVER
          value: "config-server:50051"
        - name: "CONFIG_DIR"
          value: "/fbc"
        - name: "CONFIG_PRODUCT"
          value: "am"
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 180Mi
            cpu: 100m
        volumeMounts:
        - name: fbc
          mountPath: /fbc

      # TODO - add sidecar to check for changes
      terminationGracePeriodSeconds: 10
      # Shared volume that holds the AM configuration.
      volumes:
      - name: fbc
        emptyDir: {}
      - name: am-secrets
        projected:
          sources:
          - secret:
              name: am-passwords
          - secret:
              name: am-keystore
      - name: amster-key
        secret:
          secretName: amster
          items:
          - key: id_rsa.pub
            path: authorized_keys
      - name: truststore
        secret:
          secretName: truststore-pem
      - name: new-truststore
        emptyDir: {}
