kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/name: am
  app.kubernetes.io/instance: am
  app.kubernetes.io/component: am
  app.kubernetes.io/part-of: forgerock
  tier: middle
  app: am
resources:
- deployment.yaml
- service.yaml
# Need k8s 1.18+ to enable HPA
# - hpa.yaml
images:
- name: conf
  newName: gcr.io/forgeops-public/config_client
- name: am
  newName: gcr.io/forgerock-io/am-base/pull-requests
  newTag: 7.2.0-PR-14982-2-9ea1639198d9d40c12866e8f4522abcd6a73656a
  newTag: 7.2.0-PR-14982-3-9ea1639198d9d40c12866e8f4522abcd6a73656a
  # newName: gcr.io/forgerock-io/am-base/pit1
  # newTag: 7.2.0-latest-postcommit
