apiVersion: apps/v1
kind: Deployment
metadata:
  name: idm
  labels:
    app: idm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idm
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      initContainers:
      - name: config
        image: conf
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /fbc
          name: fbc
        env:
        - name: CONFIG_SERVER
          value: "config-server:50051"
        - name: "CONFIG_DIR"
          value: "/fbc"
        - name: "CONFIG_PRODUCT"
          value: "idm"

      - name: truststore-init
        image: idm
        imagePullPolicy: Always
        volumeMounts:
        - name: new-truststore
          mountPath: /truststore
        - name: truststore
          mountPath: /var/run/secrets/truststore
        command: ["/opt/openidm/bin/import-pem-certs.sh"]
        env:
        - name: TRUSTSTORE_PATH
          value: /truststore/idmtruststore
        - name: TRUSTSTORE_PASSWORD
          value: changeit
        - name: IDM_PEM_TRUSTSTORE
          value: "/var/run/secrets/truststore/cacerts"

      containers:
      - name: openidm
        image: idm
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPENIDM_REPO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ds-passwords
              key: dirmanager.pw
        - name: USERSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ds-passwords
              key: dirmanager.pw
        - name: RS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: amster-env-secrets
              key: IDM_RS_CLIENT_SECRET
        # see additional RCS Agent related config in configmap.yaml
        - name: RCS_AGENT_IDM_SECRET
          valueFrom:
            secretKeyRef:
              name: rcs-agent-env-secrets
              key: AGENT_IDM_SECRET
        - name: OPENIDM_ICF_RETRY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: RCS_AGENT_ENABLED
        - name: OPENIDM_ICF_RETRY_UPDATES_ENABLED
          valueFrom:
            configMapKeyRef:
              name: platform-config
              key: RCS_AGENT_ENABLED
        - name: JAVA_OPS
          value: "-XX:MaxRAMPercentage=65 -XX:InitialRAMPercentage=65 -XX:MaxTenuringThreshold=1 -Djava.security.egd=file:/dev/urandom -XshowSettings:vm"
        envFrom:
        - configMapRef:
            name: idm
        - secretRef:
            name: idm-env-secrets
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value: "true"
            path: /openidm/info/ping
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-OpenIDM-Username
              value: anonymous
            - name: X-OpenIDM-Password
              value: anonymous
            - name: X-OpenIDM-NoSession
              value: "true"
            path: /openidm/info/ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1280Mi
          requests:
            cpu: 250m
            memory: 768Mi
        volumeMounts:
        - mountPath: /var/run/secrets/idm
          name: idm-secrets
        - name: new-truststore
          mountPath: /opt/openidm/idmtruststore
          readOnly: true
          subPath: idmtruststore
        - mountPath: /opt/openidm/logs
          name: logs
        - mountPath: /opt/openidm/audit
          name: audit-logs
        - mountPath: /var/run/openidm/logging
          name: idm-properties
        - mountPath: /opt/openidm/resolver
          name: idm-properties
        - name: fbc
          mountPath: /opt/openidm/conf
          subPath: conf
        # Dont overlay ui
        # - name: fbc
        #   mountPath: /opt/openidm/ui
        #   subPath: ui
        - name: fbc
          mountPath: /opt/openidm/script
          subPath: script
      terminationGracePeriodSeconds: 10
      volumes:
      - name: fbc
        emptyDir: {}
      - name: idm-secrets
        secret:
          secretName: idm
      - name: new-truststore
        emptyDir: {}
      - name: truststore
        secret:
          secretName: truststore-pem
      - name: logs
        emptyDir: {}
      - name: audit-logs
        emptyDir: {}
      - name: idm-properties
        configMap:
           name: idm-properties

