timeout: 900s
options:
  env:
    - NAMESPACE=smoke
    - DEFAULT_DOCKER_REPO=gcr.io/engineering-devops

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: authenticate
  waitFor: ['-']
  args: ['container', 'clusters', 'get-credentials', 'eng-shared-2', '--region=europe-west2']

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: build-images
  waitFor: ['authenticate']
  args:
    - -c
    - |-
      ./bin/forgeops build am amster idm ds-idrepo --default-repo $$DEFAULT_DOCKER_REPO

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: nuke-environment
  waitFor: ['build-images']
  args:
    - -c
    - |-
      ./bin/forgeops delete -n $$NAMESPACE --yes

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: deploy-cdk
  waitFor: ['nuke-environment']
  args:
    - -c
    - |-
      ./bin/forgeops install --fqdn smoke.eng.forgeops.com -n $$NAMESPACE

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: smoke-tests
  waitFor: ['deploy-cdk']
  args:
    - -c
    - |-
      ./cicd/bin/smoke-tests
