timeout: 900s
options:
  env:
    - NAMESPACE=nightly
    - DEFAULT_DOCKER_REPO=gcr.io/engineering-devops
    - SET_IMAGES_LOG=/workspace/set_log.txt

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: authenticate
  waitFor: ['-']
  args: ['container', 'clusters', 'get-credentials', 'eng-shared-2', '--region=europe-west2']

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: build-images
  waitFor: ['authenticate']
  secretEnv:
    - "GIT_KEY"
  args:
    - -c
    - |-
      . ./cicd/bin/lib-git-auth.sh || { echo "failed to configure credentials" && exit 1; }
      # used for slack notification
      ./bin/set-images > $$SET_IMAGES_LOG
      ./bin/forgeops build am amster idm ds-idrepo --default-repo $$DEFAULT_DOCKER_REPO

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: nuke-environment
  waitFor: ['build-images']
  args:
    - -c
    - |-
      ./bin/forgeops delete -n $$NAMESPACE --yes

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: deploy-cdk
  waitFor: ['nuke-environment']
  args:
    - -c
    - |-
      ./bin/forgeops install --fqdn nightly.eng.forgeops.com -n $$NAMESPACE

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: smoke-tests
  waitFor: ['deploy-cdk']
  args:
    - -c
    - |-
      ./cicd/bin/smoke-tests

- name: 'gcr.io/$PROJECT_ID/skaffold:latest'
  entrypoint: bash
  id: slack-notify
  waitFor: ['smoke-tests']
  secretEnv: ['SLACK_WEBHOOK_URL', 'SLACK_FAILED_WEBHOOK_URL']
  args:
    - -c
    - |-
      ./cicd/bin/nightly-slack-notify

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/slack_webhook_url_nightly/versions/latest
      env: 'SLACK_WEBHOOK_URL'
    - versionName: projects/$PROJECT_NUMBER/secrets/slack_webhook_url_nightly_team/versions/latest
      env: 'SLACK_FAILED_WEBHOOK_URL'
    - versionName: projects/$PROJECT_NUMBER/secrets/cloudbuild-platform-config-ssh-key/versions/latest
      env: 'GIT_KEY'
