namespace: prod
commonLabels:
  app.kubernetes.io/part-of: "forgerock"
resources:
- ../../base/kustomizeConfig
- ../../base/ds/cts
- ../../base/ds/idrepo

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: platform-config
  data:
    FQDN: "prod.iam.forgeops.com"
    CERT_ISSUER: letsencrypt-prod

