apiVersion: v1
kind: Service
metadata:
  name: ds
  labels:
    component: ds
spec:
  clusterIP: None
  ports:
  - name: admin
    port: 4444
  - name: ldap
    port: 1389
  - name: ldaps
    port: 1636
  - name: http
    port: 8080
  - name: https
    port: 8443
  selector:
    app: ds
