# Deploys multi-cluster DS: ds-cts and ds-idrepo
# The namespace must be identical for all regions
resources:
  - ../../../base/kustomizeConfig
  - ../multi-cluster-secrets
  - ../../../base/ds/idrepo
  - ../../../base/ds/cts 

# The name of the services for both ds (ds-cts, ds-idrepo) are modified to include the region as a suffix
# The new name must match the 'subdomain' value in the corresponding StatefulSet (in 'patchesStrategicMerge' section)
patches:
- target:
    kind: Service
    name: ds-idrepo
  patch: |-
    - op: replace
      path: /metadata/name
      value: ds-idrepo-us
- target:
    kind: Service
    name: ds-cts
  patch: |-
    - op: replace
      path: /metadata/name
      value: ds-cts-us

# There are two main settings to pay attention to in this section
# 1) In each StatefulSet, the subdomain ('spec.template.spec.subdomain') must correspond to the service name, which includes
#    the region as a suffix
# 2) In each StatefulSet, the DS_BOOTSTRAP_REPLICATION_SERVERS must be set to match the FQDN of the DS bootstrap servers
#    Note that in a multi-cluster setting, the FQDN has the following format: '[serverName].[serviceName].[namespace].svc.cluster.local'
#         where serverName is built using number as a suffix, for example: 'ds-cts-0', 'ds-cts-1', ..., 'ds-cts-n'
#         where serviceName is built using the region as a suffix, for example 'ds-cts-europe' or 'ds-cts-us'
- path: ds-cts-old.yaml
- path: ds-idrepo-old.yaml
