# Deploys multi-cluster DS: ds-cts and ds-idrepo
# The namespace must be identical for all regions
resources:
  - ../../../../base/kustomizeConfig
  - ../../multi-cluster-secrets
  - ../../../../base/ds/idrepo
  - ../../../../base/ds/cts 

# The name of the services for both ds (ds-cts, ds-idrepo) are modified to include the region as a suffix
# The new name must match the 'subdomain' value in the corresponding StatefulSet (in 'patchesStrategicMerge' section)
patches:
- target:
    kind: Service
    name: ds-idrepo
  patch: |-
    - op: replace
      path: /metadata/name
      value: ds-idrepo-eu
    - op: add
      path: /spec/ports/5
      value: { "name": "replication", "port": 8989 }
- target:
    kind: Service
    name: ds-cts
  patch: |-
    - op: replace
      path: /metadata/name
      value: ds-cts-eu
    - op: add
      path: /spec/ports/5
      value: { "name": "replication", "port": 8989 }

- path: ds-cts-old.yaml
- path: ds-idrepo-old.yaml
