# Deploys ds-idrepo and ds-cts only. Used by PIT/Perf teams.
namespace: default
resources:
  - ../../base/kustomizeConfig
  - ../../base/7.0/ds/cts
  - ../../base/7.0/ds/idrepo

patchesStrategicMerge:
  - |-
    #Patch DS IDREPO
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: ds-idrepo
    spec:
      template:
        spec:
          containers:
            - name: ds
              resources:
                requests:
                  memory: 4Gi
                  cpu: 4
                limits:
                  memory: 4Gi
                  cpu: 4
          initContainers:
            - name: initialize
              imagePullPolicy: Always
      volumeClaimTemplates:
      - metadata:
          name: data
          annotations:
            pv.beta.kubernetes.io/gid: "0"
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 100Gi
          storageClassName: fast
