apiVersion: v1
kind: Service
metadata:
  name: dspublic
  labels:
    component: ds
spec:
  type: LoadBalancer
  ports:
  - name: ldap
    port: 1389
    targetPort: 1389
  - name: ldaps
    port: 1636
    targetPort: 1636
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: ds